### ISSUE TITLE
Faltan capturas de pantalla

### ISSUE THREAD

**Issue by LuisJoseSanchez** [RafaelGonzalezRojo/ProyectoCrud#1]
Falta una carpeta con capturas de pantalla de la aplicación.

**Comment by RafaelGonzalezRojo** [comment]
oki enseguida actulizo el github

2016-05-29 19:01 GMT+08:00 Luis José Sánchez notifications@github.com:

**Comment by RafaelGonzalezRojo** [comment]
ya subi algunas capturas de pantalla estan repositorio ProyectoCrudo -->
Naves --> Capturas_de_Pantalla no tiene pedida gracias luis por avisar nos
vemos mañana un saludo

2016-05-30 18:30 GMT+08:00 Rafael Gonzalez Rojo <
rafaelgonzalezrojo@gmail.com>:
